// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using Eagle;
//
//    var welcome = Welcome.FromJson(jsonString);

namespace PlayGround
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;


    public class RootObject
    {
        [JsonProperty("test-run")]
        public TestRun TestRun { get; set; }
    }

    public class TestRun
    {
        [JsonProperty("test-suite")]
        public TestRunTestSuite TestSuite { get; set; }
    }

    public class TestRunTestSuite
    {

        [JsonProperty("@name")]
        public string Name { get; set; }

        [JsonProperty("@fullname")]
        public string Fullname { get; set; }


        [JsonProperty("test-suite", NullValueHandling = NullValueHandling.Ignore)]
        public List<TestRunTestSuite> TestSuite { get; set; }

        [JsonProperty("test-case", NullValueHandling = NullValueHandling.Ignore)]
        public List<TestCaseElement> TestCase { get; set; }
    }



    public class TestCaseElement
    {
        [JsonProperty("@name")]
        public string Name { get; set; }

        [JsonProperty("@fullname")]
        public string Fullname { get; set; }
    }



}